export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CHANGE_USERNAME_SUCCESS="CHANGE_USERNAME_SUCCESS";
export const CHANGE_USERNAME_ERROR="CHANGE_USERNAME_ERROR";
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_ALERT = 'CLEAR_ALERT';

